import type { DashboardSummary } from "./types";

const now = new Date().toISOString();

export const premiumDashboardMock: DashboardSummary = {
  user: {
    id: "demo-user",
    email: "athlete@example.com",
    name: "Jordan",
    role: "user",
    paymentStatus: "paid",
    bookingCompleted: true,
    bookingTime: now,
    trialStartDate: now,
    trialEndDate: now,
    trialCompletedAt: null,
    streakDays: 4,
    progressPercent: 58,
  },
  modules: [
    {
      id: "day-1",
      day_number: 1,
      title: "Foundation Reset",
      description:
        "Set the standard, sharpen the win, and lock in the baseline.",
      youtube_url:
        "https://www.youtube.com/embed/KwoI0SgTJzY?rel=0&modestbranding=1",
      resources: ["Day 1 notes", "Baseline checklist"],
      created_at: now,
      watched: true,
      completed: true,
      unlocked: true,
      feedbackSubmitted: true,
      canSubmitFeedback: false,
      watchedAt: now,
      completedAt: now,
      feedbackSubmittedAt: now,
    },
    {
      id: "day-2",
      day_number: 2,
      title: "Energy Architecture",
      description:
        "Build the habits that power output without burning you out.",
      youtube_url:
        "https://www.youtube.com/embed/yTAPv6f8FfU?rel=0&modestbranding=1",
      resources: ["Hydration targets", "Morning checklist"],
      created_at: now,
      watched: true,
      completed: true,
      unlocked: true,
      feedbackSubmitted: true,
      canSubmitFeedback: false,
      watchedAt: now,
      completedAt: now,
      feedbackSubmittedAt: now,
    },
    {
      id: "day-3",
      day_number: 3,
      title: "Strength Command",
      description: "Train with intent, protect joints, and earn every rep.",
      youtube_url:
        "https://www.youtube.com/embed/M-hR9CDcQng?rel=0&modestbranding=1",
      resources: ["Rep quality cues", "Tempo guidance"],
      created_at: now,
      watched: true,
      completed: true,
      unlocked: true,
      feedbackSubmitted: true,
      canSubmitFeedback: false,
      watchedAt: now,
      completedAt: now,
      feedbackSubmittedAt: now,
    },
    {
      id: "day-4",
      day_number: 4,
      title: "Recovery Doctrine",
      description: "Sleep, stress, soreness, and hydration become feedback.",
      youtube_url:
        "https://www.youtube.com/embed/Z9f4p1oXJx0?rel=0&modestbranding=1",
      resources: ["Recovery checklist", "HRV notes"],
      created_at: now,
      watched: true,
      completed: false,
      unlocked: true,
      feedbackSubmitted: false,
      canSubmitFeedback: true,
      watchedAt: now,
      completedAt: null,
      feedbackSubmittedAt: null,
    },
    {
      id: "day-5",
      day_number: 5,
      title: "Consistency Systems",
      description: "Daily structure makes the result inevitable.",
      youtube_url:
        "https://www.youtube.com/embed/qg0VQY0q5YQ?rel=0&modestbranding=1",
      resources: ["Non-negotiables", "Execution rules"],
      created_at: now,
      watched: false,
      completed: false,
      unlocked: false,
      feedbackSubmitted: false,
      canSubmitFeedback: false,
      watchedAt: null,
      completedAt: null,
      feedbackSubmittedAt: null,
    },
    {
      id: "day-6",
      day_number: 6,
      title: "Progressive Overload",
      description: "Push forward without breaking recovery or rhythm.",
      youtube_url:
        "https://www.youtube.com/embed/3s1d8w2uPjA?rel=0&modestbranding=1",
      resources: ["Load plan", "Fatigue audit"],
      created_at: now,
      watched: false,
      completed: false,
      unlocked: false,
      feedbackSubmitted: false,
      canSubmitFeedback: false,
      watchedAt: null,
      completedAt: null,
      feedbackSubmittedAt: null,
    },
    {
      id: "day-7",
      day_number: 7,
      title: "Final Integration",
      description: "Capture the lesson and set the next phase.",
      youtube_url:
        "https://www.youtube.com/embed/xg5p6mYb6j0?rel=0&modestbranding=1",
      resources: ["Completion checklist", "Certificate download"],
      created_at: now,
      watched: false,
      completed: false,
      unlocked: false,
      feedbackSubmitted: false,
      canSubmitFeedback: false,
      watchedAt: null,
      completedAt: null,
      feedbackSubmittedAt: null,
    },
  ],
  activeDay: 4,
  currentDay: 4,
  completionPercent: 58,
  completedDays: [1, 2, 3],
  watchedVideos: [1, 2, 3, 4],
  unlockStatus: [
    {
      day_number: 1,
      unlocked: true,
      completed: true,
      feedbackSubmitted: true,
      lockedReason: null,
    },
    {
      day_number: 2,
      unlocked: true,
      completed: true,
      feedbackSubmitted: true,
      lockedReason: null,
    },
    {
      day_number: 3,
      unlocked: true,
      completed: true,
      feedbackSubmitted: true,
      lockedReason: null,
    },
    {
      day_number: 4,
      unlocked: true,
      completed: false,
      feedbackSubmitted: false,
      lockedReason: null,
    },
    {
      day_number: 5,
      unlocked: false,
      completed: false,
      feedbackSubmitted: false,
      lockedReason: "Complete the previous day and submit feedback to unlock.",
    },
    {
      day_number: 6,
      unlocked: false,
      completed: false,
      feedbackSubmitted: false,
      lockedReason: "Locked until earlier days are completed in sequence.",
    },
    {
      day_number: 7,
      unlocked: false,
      completed: false,
      feedbackSubmitted: false,
      lockedReason: "Locked until earlier days are completed in sequence.",
    },
  ],
  dailyFeedback: [
    {
      id: "fb-1",
      user_id: "demo-user",
      day_number: 1,
      mood: 7,
      energy: 8,
      understanding_level: 8,
      takeaway: "Start early, execute clean.",
      struggles: "Time management",
      questions: "How hard should the finish be?",
      commitment_score: 9,
      notes: "Keep the morning block protected.",
      created_at: now,
    },
  ],
  coachNotes: [
    {
      id: "note-1",
      user_id: "demo-user",
      admin_id: "coach-1",
      note: "Strong execution so far. Keep the cadence tight.",
      label: "high-potential",
      created_at: now,
    },
  ],
  checkIns: [],
  workouts: [
    {
      id: "gym-1",
      programType: "gym",
      day: 4,
      title: "Lower Body Strength",
      coachNotes: "Keep rest honest. No ego sets. Move crisp and controlled.",
      videoUrl:
        "https://www.youtube.com/embed/yTAPv6f8FfU?rel=0&modestbranding=1",
      completed: false,
      exercises: [
        { name: "Trap Bar Deadlift", sets: "4", reps: "5" },
        { name: "Rear-Foot Elevated Split Squat", sets: "3", reps: "8/side" },
        { name: "Lat Pulldown", sets: "3", reps: "10" },
      ],
    },
    {
      id: "home-1",
      programType: "home",
      day: 4,
      title: "Home Conditioning Circuit",
      coachNotes: "Short rest. Keep the heart rate in check and finish clean.",
      videoUrl:
        "https://www.youtube.com/embed/KwoI0SgTJzY?rel=0&modestbranding=1",
      completed: true,
      exercises: [
        { name: "Air Squat", sets: "4", reps: "15" },
        { name: "Push-Up", sets: "4", reps: "10" },
        { name: "Plank", sets: "4", reps: "30s" },
      ],
    },
  ],
  emailProgress: [
    {
      id: "e1",
      step: 1,
      subject: "Welcome + Orientation",
      sentAt: now,
      status: "read",
      openedAt: now,
      readAt: now,
    },
    {
      id: "e2",
      step: 2,
      subject: "Training Rules of Engagement",
      sentAt: now,
      status: "opened",
      openedAt: now,
    },
    {
      id: "e3",
      step: 3,
      subject: "Recovery Doctrine",
      sentAt: now,
      status: "sent",
    },
    {
      id: "e4",
      step: 4,
      subject: "Performance Review Checkpoint",
      sentAt: now,
      status: "queued",
    },
    {
      id: "e5",
      step: 5,
      subject: "Final Review Prep",
      sentAt: now,
      status: "queued",
    },
  ],
  analytics: {
    labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    energy: [6, 7, 7, 8, 8, 9, 8],
    mood: [6, 6, 7, 7, 8, 8, 9],
    performance: [5, 6, 6, 7, 7, 8, 8],
    checkInConsistency: [1, 2, 2, 3, 4, 5, 5],
    weight: [null, 201, 200.4, 200.1, 199.8, 199.3, 199],
  },
  discoveryCall: {
    booked: true,
    scheduledAt: now,
    eventId: "evt_demo_123",
    instructions: [
      "Join 5 minutes early.",
      "Bring your check-in notes.",
      "Have your training questions ready.",
    ],
  },
  finalReview: {
    title: "Final Review Scheduled",
    coachNotes:
      "Confirm results, discuss next phase, and lock the continuation path.",
    userNotes: "Keep consistency high through the last two days.",
    feedbackEnabled: true,
  },
};
